export const LEVEL_CONFIG = {
  beginner: {
    label: "🌱 초보자",
    description: "코딩은 처음! AI가 다 해줘요",
    phases: ["planning", "building", "deploying"],
  },
  intermediate: {
    label: "🌿 중급자",
    description: "코드를 읽고 수정할 수 있어요",
    phases: ["planning", "design", "setup", "development", "testing", "deploying"],
  },
  advanced: {
    label: "🌳 고급자",
    description: "아키텍처부터 배포까지 직접!",
    phases: [
      "planning",
      "design",
      "setup",
      "frontend",
      "backend",
      "integration",
      "testing",
      "pre-deploy",
      "deploying",
      "operation",
    ],
  },
};

export const ALL_PHASES = [
  {
    id: "planning",
    name: "기획",
    emoji: "🎯",
    steps: [
      { id: "1.1", title: "아이디어 정의", description: "무엇을 만들 것인가", guide: "AI에게 한 줄로 만들고 싶은 앱을 말해보세요." },
      { id: "1.2", title: "문제 정의", description: "누구의 어떤 문제를 해결하는가", guide: "이 앱이 없으면 어떤 불편이 생기는지 적어보세요." },
      { id: "1.3", title: "타겟 사용자 정의", description: "주 사용자층 결정", guide: "누가 쓸 앱인지 구체적으로 정하세요." },
      { id: "1.4", title: "핵심 기능 목록", description: "MVP 범위 기능 나열", guide: "필수 기능만 3~5개 적어보세요." },
      { id: "1.5", title: "우선순위 결정", description: "기능별 중요도 매트릭스", guide: "기능에 필수/있으면 좋음/나중에 태그를 붙여보세요." },
      { id: "1.6", title: "일정 수립", description: "마감일 기준 역산 스케줄", guide: "마감일부터 거꾸로 계산하세요." },
    ],
  },
  {
    id: "design",
    name: "설계",
    emoji: "🎨",
    steps: [
      { id: "2.1", title: "사용자 플로우 설계", description: "사용자 경로 정의", guide: "사용자가 목표를 달성할 때까지의 경로를 그려보세요." },
      { id: "2.2", title: "화면 목록 정리", description: "필요한 페이지 나열", guide: "홈, 로그인, 대시보드, 설정 등 페이지를 나열하세요." },
      { id: "2.3", title: "와이어프레임 제작", description: "레이아웃 스케치", guide: "종이나 피그마에 대략적인 구조를 그려보세요." },
      { id: "2.4", title: "UI 디자인", description: "색상, 폰트, 스타일 결정", guide: "메인 색상 2~3개와 폰트 1~2개만 정하면 충분합니다." },
      { id: "2.5", title: "데이터 모델 설계", description: "DB 스키마 구조", guide: "어떤 데이터를 저장할지 정리하세요." },
      { id: "2.6", title: "API 설계", description: "엔드포인트 목록 정의", guide: "프론트와 백엔드가 주고받을 경로를 정하세요." },
      { id: "2.7", title: "기술 스택 결정", description: "프레임워크, 인프라 선택", guide: "익숙한 스택을 우선 선택하세요." },
    ],
  },
  {
    id: "setup",
    name: "환경 구축",
    emoji: "⚙️",
    steps: [
      { id: "3.1", title: "프로젝트 초기화", description: "보일러플레이트 생성", guide: "프로젝트 뼈대를 먼저 만드세요." },
      { id: "3.2", title: "Git 저장소 생성", description: "레포 생성 + 초기 커밋", guide: "GitHub 저장소를 만들고 첫 커밋을 올리세요." },
      { id: "3.3", title: "개발 환경 설정", description: "린터, 포매터 설정", guide: "ESLint, Prettier를 설정하세요." },
      { id: "3.4", title: "의존성 설치", description: "패키지 설치", guide: "필요한 라이브러리를 설치하세요." },
      { id: "3.5", title: "환경변수 설정", description: ".env, 시크릿 관리", guide: "민감한 정보는 .env에 넣고 커밋하지 마세요." },
      { id: "3.6", title: "폴더 구조 구성", description: "디렉토리 컨벤션", guide: "components, utils 같은 폴더를 정리하세요." },
    ],
  },
  {
    id: "frontend",
    name: "프론트엔드",
    emoji: "🖥️",
    steps: [
      { id: "4.1", title: "공통 레이아웃", description: "헤더, 푸터, 네비게이션", guide: "모든 페이지의 공통 구조를 먼저 만드세요." },
      { id: "4.2", title: "페이지 라우팅", description: "페이지 간 이동 구조", guide: "각 페이지와 링크를 연결하세요." },
      { id: "4.3", title: "공통 컴포넌트", description: "버튼, 폼, 카드 등", guide: "재사용할 컴포넌트를 먼저 만드세요." },
      { id: "4.4", title: "각 화면 UI 구현", description: "페이지별 화면 구현", guide: "와이어프레임을 보며 실제 UI를 만드세요." },
      { id: "4.5", title: "상태 관리", description: "데이터 흐름 관리", guide: "컴포넌트 간 공유 데이터 흐름을 정하세요." },
      { id: "4.6", title: "반응형 처리", description: "모바일/데스크탑 대응", guide: "화면 크기별 스타일을 적용하세요." },
    ],
  },
  {
    id: "backend",
    name: "백엔드",
    emoji: "🔧",
    steps: [
      { id: "5.1", title: "DB 생성", description: "데이터베이스 구축", guide: "저장할 데이터를 위한 DB를 준비하세요." },
      { id: "5.2", title: "API 구현", description: "CRUD 로직 작성", guide: "기본 CRUD API를 만드세요." },
      { id: "5.3", title: "인증/인가", description: "로그인, 권한 처리", guide: "로그인과 권한 체크를 구현하세요." },
      { id: "5.4", title: "비즈니스 로직", description: "핵심 기능 서버 로직", guide: "앱의 고유 로직을 구현하세요." },
      { id: "5.5", title: "외부 API 연동", description: "3rd party 서비스 연결", guide: "외부 서비스를 연결하고 키를 안전하게 관리하세요." },
      { id: "5.6", title: "에러 처리", description: "예외 상황 대응", guide: "친절한 에러 메시지를 보여주세요." },
    ],
  },
  {
    id: "integration",
    name: "통합",
    emoji: "🔗",
    steps: [
      { id: "6.1", title: "프론트-백 연결", description: "API 호출 연동", guide: "프론트에서 API를 호출하고 데이터를 받아보세요." },
      { id: "6.2", title: "데이터 바인딩 확인", description: "실제 데이터 동작 확인", guide: "화면에 데이터가 제대로 표시되는지 확인하세요." },
      { id: "6.3", title: "전체 플로우 테스트", description: "시나리오 통과 확인", guide: "회원가입부터 로그아웃까지 전체 흐름을 테스트하세요." },
      { id: "6.4", title: "버그 수정", description: "발견된 이슈 해결", guide: "발견된 버그를 하나씩 해결하세요." },
    ],
  },
  {
    id: "testing",
    name: "테스트",
    emoji: "🧪",
    steps: [
      { id: "7.1", title: "단위 테스트", description: "개별 함수 테스트", guide: "각 함수가 올바른 결과를 반환하는지 테스트하세요." },
      { id: "7.2", title: "통합 테스트", description: "API+DB 연동 테스트", guide: "API와 DB가 제대로 연동되는지 확인하세요." },
      { id: "7.3", title: "E2E 테스트", description: "시나리오 자동화 테스트", guide: "사용자 시나리오를 자동화 테스트하세요." },
      { id: "7.4", title: "성능 테스트", description: "로딩, 응답 시간 측정", guide: "로딩 속도를 측정하고 개선해보세요." },
      { id: "7.5", title: "보안 점검", description: "취약점 스캔", guide: "기본 보안 취약점을 점검하세요." },
    ],
  },
  {
    id: "pre-deploy",
    name: "배포 준비",
    emoji: "📦",
    steps: [
      { id: "8.1", title: "빌드 최적화", description: "번들, 이미지 최적화", guide: "프로덕션 빌드를 확인하세요." },
      { id: "8.2", title: "환경별 설정 분리", description: "dev/staging/prod 구분", guide: "환경변수를 분리하세요." },
      { id: "8.3", title: "CI/CD 구축", description: "자동 빌드/배포 설정", guide: "푸시 시 자동 빌드 파이프라인을 만드세요." },
      { id: "8.4", title: "도메인 & SSL", description: "커스텀 도메인, HTTPS", guide: "도메인과 HTTPS를 설정하세요." },
      { id: "8.5", title: "모니터링 설정", description: "에러 추적, 로그 수집", guide: "에러 추적 도구를 연결하세요." },
    ],
  },
  {
    id: "deploying",
    name: "배포",
    emoji: "🚀",
    steps: [
      { id: "9.1", title: "스테이징 배포", description: "테스트 환경 배포", guide: "테스트 환경에 먼저 배포하세요." },
      { id: "9.2", title: "최종 검증", description: "스테이징 전체 확인", guide: "배포 전에 최종 점검을 하세요." },
      { id: "9.3", title: "프로덕션 배포", description: "실제 서비스 배포", guide: "실제 서비스에 배포하세요." },
      { id: "9.4", title: "배포 후 확인", description: "정상 동작 모니터링", guide: "배포 후 정상 동작을 확인하세요." },
    ],
  },
  {
    id: "operation",
    name: "운영",
    emoji: "📈",
    steps: [
      { id: "10.1", title: "피드백 수집", description: "사용자 의견 모으기", guide: "사용자 피드백을 모아보세요." },
      { id: "10.2", title: "버그 대응", description: "이슈 추적 & 핫픽스", guide: "버그를 이슈로 관리하세요." },
      { id: "10.3", title: "기능 업데이트", description: "신규 기능 추가", guide: "피드백을 바탕으로 새 기능을 추가하세요." },
      { id: "10.4", title: "성능 개선", description: "병목 분석 & 최적화", guide: "느린 부분을 최적화하세요." },
    ],
  },
];
